esphome:
  name: tuerklingel
  friendly_name: tuerklingel

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "***"

ota:
  password: "***"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tuerklingel Fallback Hotspot"
    password: "***"

captive_portal:
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
    name: "Tuerklingel Wohnungstür"
    device_class: SOUND

  - platform: gpio
    pin:
      number: GPIO4
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
    name: "Tuerklingel Haustür"
    device_class: SOUND
    
switch:
  - platform: gpio
 #   pin: GPIO16
    pin:
      number: 16
      inverted: true
    id: relay
    name: "Tueroeffner"
    on_turn_on:
    - delay: 5000ms
    - switch.turn_off: relay